### ISSUE TITLE
Splicing req.body hangs SCGI.Server

### ISSUE THREAD

**Issue by Bob131** [valum-framework/valum#128]
```
app.post(null, (req, res) => {
    var buffer = new MemoryOutputStream.resizable();
    buffer.splice(req.body, OutputStreamSpliceFlags.CLOSE_SOURCE);
    var data = Soup.Form.decode((string) buffer.get_data());
}
```

The above code when used with `VSGI.SCGI.Server` hang on `buffer.splice` for some time before finally `GLib-CRITICAL **: g_strsplit: assertion 'string != NULL' failed` is emitted, presumably from `Soup.Form.decode()`.

This works as expected with VSGI.Soup

**Comment by arteymix** [comment]
This issue is addressed by #121, accumulating a stream in a buffer is tricky:
 
 - you cannot call `get_data` if you haven't closed the stream
 - the buffer returned by `get_data` does not have a size

This is why you have to specify `OutputStreamSpliceFlags.CLOSE_TARGET` and set the buffer size with `get_data_size`.

The reason it works with libsoup-2.4 is that the stream is only a memory-stream over existing data, so it does not face the problems I mentioned.

The cleanest way to perform the operation is available in this diff: https://github.com/valum-framework/valum/pull/121/files

If the documentation is wrong, it would be very important to update it.

**Comment by Bob131** [comment]
I must admit, this is where it all gets fuzzy for me. In my measly five or so years of working in Python, I've never had to get my hands dirty with nitty-gritty implementation details since everything is so neatly abstracted. So forgive me if on this I merely nod and leave the handling of this issue to you. If nothing else, I can cheer for you from the sidelines and keep an eye out for bugs easy to shake out of the tree :)

If I may say, I'm very fond of DRY libraries that provide loads of convenience functions to make working with the API a super-buttery experience. Things like `req.flatten` (or even pre-parsing detected form data into a HashTable like `req.params`) are very welcome! No pressure, of course; I have no doubt this library is still in infancy

**Comment by arteymix** [comment]
Effectively and it should be noted that Valum is not _yet_ a general purpose web framework, so many utilities are missing to perform body interpretation. It will come, but it is also important to focus on solid basis before bringing these features in.

Valum will _eventually_ become that DRY library you've been dreaming of. VSGI have to remain low-level and minimal. In short, VSGI let you build a DRY framework like Valum and Valum let you write DRY code for your application.

Pre-parsing is not a good approach for many reasons:

 - implicitly use memory to store the representation: you'll realize that VSGI has an insignificant memory trace and this is critical in vertical scaling (memory can be a bottleneck)
 - all data formats does not sum up in a `HashTable`
 - breaks the very idea of filtering: Valum let you build a pipeline of transformation before actually parsing the data (decompression, charset encoding, ...)
 - lose generality as the message can contain any content type and we cannot possibly parse all of them

I would rather have utilities to parse common data format and use a Converter when it can be applied on a stream (like base64 decoding).

I am using Valum for an academic project and since I am dealing with JSON documents, I really enjoy stream-based processing:

```vala
var parser = new Json.Parser ();

if (parser.load_from_stream (req.body)) {
    var root = parser.get_root ();
}
```

The `0.3` will target many aspects of traditional web development:

 - multipart body (e.g. file submission in form)
 - content negotiation (delivering resource in different representation like XML or JSON)
 - filters for compression, buffering, ...
 - flatten, of course
 - reverse a route path given a set of parameters

This is why I like to have feedback as it let me identify requirements and what to introduce next. And as you know, features introduce bugs and they have to be carefully selected to reach realistic deadlines.

**Comment by arteymix** [comment]
I'll update the documentation until `flatten` is introduced.
