### ISSUE TITLE
about TODO's hiredis vapi 

### ISSUE THREAD

**Issue by Matrix-Zhang** [valum-framework/valum#176]
i was wriiten the binding...

https://github.com/Matrix-Zhang/vala-bindings/blob/master/vapi/hiredis.vapi

**Comment by arteymix** [comment]
Few suggestions:

 - use enums for error and reply codes
 - use a class for `Context` and turn `connect` into a constructor
 - make `command` a method for `Context`
 - use a list for `elements`, the size is already available through `elements.length`

I can add a link in the docs (see [here](here](http://docs.valum-framework.org/en/latest/recipes/persistence/)) and a code example.

Otherwise, I suggest that you submit the binding to nemequ/vala-extra-vapis repository.

There'a also [redis-glib](https://github.com/chergert/redis-glib), which is a handy wrapper with async support that provides Vala bindings.
