### ISSUE TITLE
Accessing with a wrong method should return a 405

### ISSUE THREAD

**Issue by Ferruck** [valum-framework/valum#58]
When trying to access a an URL that is only mapped to a specific method with another method (e.g. `GET /index/` is mapped, trying `POST /index/`) a `405 Method Not Allowed` should be returned. At the moment a `404 File Not Found` is returned which is not exactly what's wrong.

**Comment by arteymix** [comment]
Internally we use a matcher (not raw URI) so we cannot tell easily if a `405` has occured.

One way of performing this would be to try to match the Request with other defined HTTP methods and fill the `Allow` header consequently. It's costly, but since it is a failure case, it shouldn't be a performance issue.

It's an interesting feature though and it will likely involve the [Router.handle](https://github.com/valum-framework/valum/blob/master/src/router.vala#L225) function if you want to give it a try ;)

**Comment by Ferruck** [comment]
It was quite easy to implement but indeed it's quite costly. But as you said it's a failure case and as I think an important one, as it gives valuable debugging information.
